import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect, useContext } from "react";
import {
  isProd,
  apiUrlProd,
  apiUrlLocal,
  photoUrlProd,
  photoUrlLocal,
} from "env";
import LocaleContext from "@context/languageContext";
import { LocaleContextType } from "@schema/LocaleContextType";
import Nav from "@src/components/Nav";
import FooterGeneric from "@components/FooterGeneric";
import SocialMediaShare from "@components/SocialMediaShare";
import { Doctor } from "@models/Doctor";
import styles from "@styles/DoctorPage.module.css";

const fetchDoctor = async (id: string, currentLocale: string) => {
  var requestOptions: RequestInit = {
    method: "GET",
    redirect: "follow",
  };

  var tempBaseUrl = "";
  if (isProd) {
    tempBaseUrl = `${apiUrlProd}/doctors/${id}?populate=*&locale=${currentLocale}`;
  } else {
    tempBaseUrl = `${apiUrlLocal}/doctors/${id}?populate=*&locale=${currentLocale}`;
  }

  const res = await fetch(tempBaseUrl, requestOptions);
  const data = await res.json();
  return data.data;
};

export default function DoctorPage() {
  const [doctor, setDoctor] = useState<Doctor>();

  const router = useRouter();
  // const { name, doctorId } = router.query;

  const { currentLocale } = useContext(LocaleContext) as LocaleContextType;

  useEffect(() => {
    if (window.FB) {
      window.FB.XFBML.parse();
    }
  }, []);

  useEffect(() => {
    if (router.isReady) {
      const getDoctor = async () => {
        const { name, doctorId } = router.query;
        if (!doctorId) return null;
        const doctor = await fetchDoctor(doctorId as string, currentLocale);
        setDoctor(doctor);
      };

      getDoctor();
    }
  }, [router.isReady]);

  var tempPhotoUrl = "";
  if (isProd) {
    tempPhotoUrl = photoUrlProd;
  } else {
    tempPhotoUrl = photoUrlLocal;
  }

  return (
    <>
      <Head>
        <title>{doctor?.attributes.doctorName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gfai_logo.ico" />
      </Head>

      <Nav isBlackBackground={true} />

      <main>
        <div className={styles.main_container}>
          <section className={styles.service_header}>
            <SocialMediaShare />
          </section>

          <div className={styles.doctor_info}>
            <div className={styles.doctor_image}>
              <img
                src={
                  tempPhotoUrl +
                  doctor?.attributes.doctorIcon.data.attributes.url
                }
              />
            </div>

            <div className={styles.doctor_biography}>
              <p
                dangerouslySetInnerHTML={{
                  __html: doctor?.attributes.doctorBiography,
                }}
              ></p>
            </div>
          </div>

          {/* <div id="fb-root"></div> */}
          <div
            className="fb-comments"
            data-href="https://developers.facebook.com/docs/plugins/comments#configurator"
            data-width=""
            data-numposts="10"
          ></div>
        </div>
      </main>
      <FooterGeneric />
    </>
  );
}
