import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import {
  isProd,
  apiUrlProd,
  apiUrlLocal,
  photoUrlProd,
  photoUrlLocal,
} from "../../env";
import FooterGeneric from "../../components/FooterGeneric";
import SocialMediaShare from "../../components/SocialMediaShare";
import { Doctor } from "../../components/models/Doctor";
import styles from "../../styles/DoctorPage.module.css";

const fetchDoctor = async (id: string) => {
  var requestOptions: RequestInit = {
    method: "GET",
    redirect: "follow",
  };

  var tempBaseUrl = "";
  if (isProd) {
    tempBaseUrl = `${apiUrlProd}/doctors/${id}?populate=*`;
  } else {
    tempBaseUrl = `${apiUrlLocal}/doctors/${id}?populate=*`;
  }

  const res = await fetch(tempBaseUrl, requestOptions);
  const data = await res.json();
  return data.data;
};

export default function DoctorPage() {
  const [doctor, setDoctor] = useState<Doctor>();

  const router = useRouter();
  const { name, doctorId } = router.query;

  useEffect(() => {
    const getDoctor = async () => {
      const doctor = await fetchDoctor(doctorId as string);
      setDoctor(doctor);
    };

    getDoctor();
  }, []);

  var tempPhotoUrl = "";
  if (isProd) {
    tempPhotoUrl = photoUrlProd;
  } else {
    tempPhotoUrl = photoUrlLocal;
  }

  return (
    <>
      <Head>
        <title>{doctor?.attributes.doctorName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main_container}>
          <section className={styles.service_header}>
            <SocialMediaShare />
          </section>

          <div className={styles.doctor_info}>
            <div className={styles.doctor_image}>
              <img
                src={
                  tempPhotoUrl +
                  doctor?.attributes.doctorIcon.data.attributes.url
                }
              />
            </div>

            <div className={styles.doctor_biography}>
              <p>{doctor?.attributes.doctorBiography}</p>
            </div>
          </div>
        </div>
      </main>
      <FooterGeneric />
    </>
  );
}
